# Generated by Copilot 
from setuptools import setup, find_packages

setup(
    name="social_media_functions",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "datascience",
        "pandas",
        "numpy"
    ],
)
