# shared code among objects
from datetime import datetime
from zoneinfo import ZoneInfo 

COLS = [
    "object_type",
    "action_type",
    "actor",
    "target",
    "value",
    "timestamp",
    "timestamp_unix",
]
# code generated by chatGPT
def format_timestamp(unix_ts: int, tz: str) -> str:
    dt_utc = datetime.fromtimestamp(unix_ts, tz=ZoneInfo("UTC"))
    dt_local = dt_utc.astimezone(ZoneInfo(tz))
    return dt_local.strftime("%Y-%m-%d %I:%M:%S %p %Z")


def rows_to_table(rows):
    try:
        from datascience import Table
    except ImportError:
        import pandas as pd
        if not rows:
            return pd.DataFrame(columns=COLS)

        df = pd.DataFrame(rows)
        for c in COLS:
            if c not in df.columns:
                df[c] = ""
        return df[COLS]

    if not rows:
        return Table().with_columns(*sum(([c, []] for c in COLS), []))

    data = {c: [r.get(c, "") for r in rows] for c in COLS}

    return Table().with_columns(
        "object_type", data["object_type"],
        "action_type", data["action_type"],
        "actor", data["actor"],
        "target", data["target"],
        "value", data["value"],
        "timestamp", data["timestamp"],
        "timestamp_unix", data["timestamp_unix"],
    )
