import json
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo  # Python 3.9+


def _rows_to_table(rows):

    # Convert rows into a datascience.Table.
    # Falls back to pandas.DataFrame if datascience isn't installed.
    # This version allows both pandas and datascience import users 
 
    try:
        from datascience import Table
    except ImportError:
        # Fallback (still usable outside datascience-based classes)
        import pandas as pd
        return pd.DataFrame(rows)

    if not rows:
        # Create an empty Table with expected columns 
        return Table().with_columns(
            "object_type", [],
            "action_type", [],
            "actor", [],
            "target", [],
            "value", [],
            "timestamp", [],
            "timestamp_unix", [],
        )

    # Ensure consistent column order
    # Code Generated by ChatGPT
    cols = ["object_type", "action_type", "actor", "target", "value", "timestamp", "timestamp_unix"]
    data = {c: [r.get(c, "") for r in rows] for c in cols}

    return Table().with_columns(
        "object_type", data["object_type"],
        "action_type", data["action_type"],
        "actor", data["actor"],
        "target", data["target"],
        "value", data["value"],
        "timestamp", data["timestamp"],
        "timestamp_unix", data["timestamp_unix"],
    )


def story_likes(path: str, tz: str = "America/New_York"):

    # Parse Instagram story_likes.json into a table.
    #Returns: datascience.Table if datascience is installed, otherwise pandas.DataFrame

    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    rows = []
    items = data.get("story_activities_story_likes", [])

    for item in items:
        actor = item.get("title", "") or ""

        for entry in item.get("string_list_data", []) or []:
            unix_ts = entry.get("timestamp")
            if unix_ts is None:
                continue

            try:
                unix_ts = int(unix_ts)
            except (TypeError, ValueError):
                continue

            dt_utc = datetime.fromtimestamp(unix_ts, tz=ZoneInfo("UTC"))
            dt_local = dt_utc.astimezone(ZoneInfo(tz))
            formatted_time = dt_local.strftime("%Y-%m-%d %I:%M:%S %p %Z")

            rows.append(
                {
                    "object_type": "story",
                    "action_type": "like",
                    "actor": actor,
                    "target": "",
                    "value": "",
                    "timestamp": formatted_time,
                    "timestamp_unix": unix_ts,
                }
            )

    return _rows_to_table(rows)
