import json
from pathlib import Path
from social_media_parser.utils import rows_to_table, format_timestamp


def instagram_stories(folder_path: str, tz: str = "America/New_York"):

    # Parse an entire folder of Instagram JSON files and return one combined table of all story interactions (likes + poll responses).
    # Works with both Pandas and Datascience Import
   
    folder = Path(folder_path)

    if not folder.exists() or not folder.is_dir():
        raise FileNotFoundError(f"Folder not found: {folder}")

    rows = []

    # Find all JSON files inside folder (including subfolders)
    # Code Generated by ChatGPT
    json_files = sorted(folder.rglob("*.json"))

    if not json_files:
        return rows_to_table([])

    for fp in json_files:
        try:
            with open(fp, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            # Skip invalid JSON files
            continue

        if not isinstance(data, dict):
            continue

 
        # Story Likes
        if "story_activities_story_likes" in data:
            for item in data.get("story_activities_story_likes", []) or []:
                actor = item.get("title", "") or ""

                for entry in item.get("string_list_data", []) or []:
                    unix_ts = entry.get("timestamp")
                    if unix_ts is None:
                        continue

                    try:
                        unix_ts = int(unix_ts)
                    except (TypeError, ValueError):
                        continue

                    rows.append({
                        "object_type": "story",
                        "action_type": "like",
                        "actor": actor,
                        "target": "",
                        "value": "",
                        "timestamp": format_timestamp(unix_ts, tz),
                        "timestamp_unix": unix_ts,
                    })

     
        # Story Poll Responses
        if "story_activities_polls" in data:
            for item in data.get("story_activities_polls", []) or []:
                actor = item.get("title", "") or ""

                for entry in item.get("string_list_data", []) or []:
                    unix_ts = entry.get("timestamp")
                    if unix_ts is None:
                        continue

                    try:
                        unix_ts = int(unix_ts)
                    except (TypeError, ValueError):
                        continue

                    value = entry.get("value", "") or ""

                    rows.append({
                        "object_type": "story",
                        "action_type": "poll_response",
                        "actor": actor,
                        "target": "",
                        "value": value,
                        "timestamp": format_timestamp(unix_ts, tz),
                        "timestamp_unix": unix_ts,
                    })

    return rows_to_table(rows)
